-- Non-auth module schema (catalog, bidding, order, notification, wallet)

CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    parent_id INTEGER,
    CONSTRAINT fk_categories_parent
        FOREIGN KEY (parent_id)
        REFERENCES categories (id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_categories_parent_id ON categories (parent_id);

CREATE TABLE IF NOT EXISTS listings (
    id UUID NOT NULL PRIMARY KEY,
    seller_id UUID NOT NULL,
    category_id INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    image_url VARCHAR(255),
    starting_price NUMERIC(38, 2) NOT NULL,
    reserve_price NUMERIC(38, 2) NOT NULL,
    current_price NUMERIC(38, 2) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    status VARCHAR(32) NOT NULL,
    winner_id UUID,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_listings_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT chk_listings_status CHECK (status IN ('DRAFT', 'ACTIVE', 'EXTENDED', 'CLOSED', 'WON', 'UNSOLD')),
    CONSTRAINT chk_listings_end_after_start CHECK (end_time > start_time)
);

CREATE INDEX IF NOT EXISTS idx_listings_category_id ON listings (category_id);
CREATE INDEX IF NOT EXISTS idx_listings_seller_id ON listings (seller_id);
CREATE INDEX IF NOT EXISTS idx_listings_status ON listings (status);

CREATE TABLE IF NOT EXISTS bids (
    id UUID NOT NULL PRIMARY KEY,
    listing_id UUID NOT NULL,
    bidder_id UUID NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_bids_listing FOREIGN KEY (listing_id) REFERENCES listings (id) ON DELETE CASCADE,
    CONSTRAINT chk_bids_status CHECK (status IN ('ACCEPTED', 'OUTBID', 'WON'))
);

CREATE INDEX IF NOT EXISTS idx_bids_listing_id ON bids (listing_id);
CREATE INDEX IF NOT EXISTS idx_bids_bidder_id ON bids (bidder_id);
CREATE INDEX IF NOT EXISTS idx_bids_listing_bidder ON bids (listing_id, bidder_id);

CREATE TABLE IF NOT EXISTS orders (
    id UUID NOT NULL PRIMARY KEY,
    listing_id UUID NOT NULL,
    buyer_id UUID NOT NULL,
    seller_id UUID NOT NULL,
    total_amount NUMERIC(38, 2) NOT NULL,
    status VARCHAR(32) NOT NULL,
    tracking_number VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_orders_listing FOREIGN KEY (listing_id) REFERENCES listings (id),
    CONSTRAINT chk_orders_status CHECK (status IN ('PENDING', 'PACKED', 'SHIPPED', 'COMPLETED', 'DISPUTED'))
);

CREATE INDEX IF NOT EXISTS idx_orders_buyer_id ON orders (buyer_id);
CREATE INDEX IF NOT EXISTS idx_orders_listing_id ON orders (listing_id);

CREATE TABLE IF NOT EXISTS notifications (
    id UUID NOT NULL PRIMARY KEY,
    user_id UUID NOT NULL,
    type VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_created_at ON notifications (user_id, created_at);

CREATE TABLE IF NOT EXISTS notification_preferences (
    id UUID NOT NULL PRIMARY KEY,
    user_id UUID NOT NULL UNIQUE,
    email_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    push_enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS wallet (
    id UUID NOT NULL PRIMARY KEY,
    sample_column VARCHAR(50)
);

