spring.application.name=bidmart-core

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/bidmart_db}
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=${DATABASE_PASSWORD:qowiy1416}

spring.jpa.hibernate.ddl-auto=update

# Midtrans config (tambahkan di sini)
midtrans.server-key=${MIDTRANS_SERVER_KEY}
midtrans.client-key=${MIDTRANS_CLIENT_KEY}
midtrans.is-production=false