spring.config.activate.on-profile=prod

spring.jpa.hibernate.ddl-auto=validate

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:https://bidmart.store}
app.cors.allowed-origin-patterns=${APP_CORS_ALLOWED_ORIGIN_PATTERNS:https://*.bidmart.store}
app.cors.allow-credentials=${APP_CORS_ALLOW_CREDENTIALS:true}
auth.cookie.same-site=${AUTH_COOKIE_SAME_SITE:None}
auth.cookie.secure=${AUTH_COOKIE_SECURE:true}
auth.registration.verification-frontend-base-url=${AUTH_REGISTRATION_VERIFICATION_FRONTEND_BASE_URL:https://bidmart.store}

midtrans.is-production=true
