services:
  postgres:
    image: postgres:16
    container_name: bidmart-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bidmart_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
