//! Axum request handlers: thin glue between HTTP and use cases.

use axum::extract::{Path, State};
use axum::Json;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::adapter::http::error::ApiError;
use crate::adapter::http::routes::AppState;
use crate::app::dto::{GetHighestBidCommand, PlaceBidCommand, RegisterListingCommand};

/// POST /api/listing/{id}/bids request body.
#[derive(Debug, Deserialize)]
pub struct BidRequest {
    pub buyer_id: Uuid,
    pub bid_amount: i64,
}

/// Bid response returned by place_bid.
#[derive(Debug, Serialize)]
pub struct BidResponse {
    pub bid_id: Uuid,
    pub listing_id: Uuid,
    pub buyer_id: Uuid,
    pub bid_amount: i64,
}

#[derive(Debug, Serialize)]
pub struct HighestBidResponse {
    pub buyer_id: Uuid,
    pub bid_amount: i64,
}

/// GET /health
pub async fn health_check() -> &'static str {
    "Auction Service is running!"
}

/// GET /api/health/status
pub async fn chained_health(State(_state): State<AppState>) -> Json<serde_json::Value> {
    Json(serde_json::json!({
        "service": "bidmart-auction",
        "status": "UP"
    }))
}

/// POST /api/listing/{listing_id}/bids
///
/// Requires JWT authentication (TODO: implement JWT middleware).
/// Includes idempotency mechanism to prevent duplicate bids.
pub async fn place_bid(
    State(state): State<AppState>,
    Path(listing_id): Path<Uuid>,
    Json(body): Json<BidRequest>,
) -> Result<Json<BidResponse>, ApiError> {
    // TODO: Extract buyer_id from JWT token, not from request body
    // For now, accept buyer_id from body (skeleton)
    println!("Received place bid request for listing: {}", listing_id);

    let cmd = PlaceBidCommand {
        buyer_id: body.buyer_id,
        listing_id,
        bid_amount: body.bid_amount,
    };

    let result = state.place_bid.execute(cmd).await?;

    Ok(Json(BidResponse {
        bid_id: result.bid_id,
        listing_id: result.listing_id,
        buyer_id: result.buyer_id,
        bid_amount: result.bid_amount,
    }))
}

/// GET /api/listing/{listing_id}/bids/highest
///
/// Returns the current highest bid for the specified listing.
pub async fn get_highest_bid(
    State(state): State<AppState>,
    Path(listing_id): Path<Uuid>,
) -> Result<Json<Option<HighestBidResponse>>, ApiError> {
    let cmd = GetHighestBidCommand { listing_id };

    let result = state.get_highest_bid.execute(cmd).await?;

    let response = result.map(|res| HighestBidResponse {
        buyer_id: res.buyer_id,
        bid_amount: res.bid_amount,
    });

    Ok(Json(response))
}

/// POST /api/listing/new request body.
#[derive(Debug, Deserialize)]
pub struct RegisterListingRequest {
    pub id: Uuid, // Usually generated by client for idempotency or server for new records
    pub seller_id: Uuid,
    pub starting_price: i64,
    pub start_time: chrono::DateTime<chrono::Utc>,
    pub end_time: chrono::DateTime<chrono::Utc>,
    pub minimum_increment: i64,
}

/// Response returned by register_listing.
#[derive(Debug, Serialize)]
pub struct RegisterListingResponse {
    pub listing_id: Uuid,
}

/// POST /api/listing/new
///
/// Registers a new auction listing in the system.
pub async fn register_listing(
    State(state): State<AppState>,
    Json(body): Json<RegisterListingRequest>,
) -> Result<Json<RegisterListingResponse>, ApiError> {
    tracing::info!("Received register listing request: id={}", body.id);

    let cmd = RegisterListingCommand {
        id: body.id,
        seller_id: body.seller_id,
        starting_price: body.starting_price,
        start_time: body.start_time,
        end_time: body.end_time,
        minimum_increment: body.minimum_increment,
    };

    let result = state.register_listing.execute(cmd).await?;

    Ok(Json(RegisterListingResponse {
        listing_id: result.listing_id,
    }))
}
